// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgauzrtohimjaohlmhxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnYXV6cnRvaGltamFvaGxtaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyODQxODAsImV4cCI6MjA4NDg2MDE4MH0.mg46RMSXHJON1PeiXvyXp4rtotJ3210BSeECV_0SKAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});